# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    allow:
      - dependency-type: "all"
    registries:
      - private-repo
registries:
  private-repo:
    type: "git"
    url: "https://github.com/huaminghuangtw/Second-Brain.git"
    token: "${{secrets.DEPENDABOT_TOKEN}}"
